name: Manual Workflow

on:
    workflow_dispatch

jobs:
    branch_info:
        runs-on: ubuntu-latest

        outputs:
            branch_name: ${{ steps.hash.outputs.branch_name }}
            branch_sha: ${{ steps.hash.outputs.branch_sha }}

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: FranzDiebold/github-env-vars-action@v2.7.0

            - name: Generate Branch SHA
              id: hash
              env:
                  BRANCH_NAME: ${{ env.CI_ACTION_REF_NAME_SLUG }}
              run: |
                  echo "OUTPUT=$(echo -n $BRANCH_NAME | openssl dgst -sha256 -binary | xxd -p)"
                  echo "branch_sha=${OUTPUT}" >> $env:GITHUB_OUTPUT

            - name: Set Branch Name Output
              env:
                  BRANCH_NAME: ${{ env.CI_ACTION_REF_NAME_SLUG }}
              run: |
                  echo "branch_name=$BRANCH_NAME" >> $env:GITHUB_OUTPUT

    execute:
      needs: [branch_info]
      runs-on: ubuntu-latest

      steps: 
        - name: Branch Name
          run: echo ${{needs.branch_info.outputs.branch_name}}

        - name: Branch SHA
          run: echo ${{needs.branch_info.outputs.branch_sha}}
