name: Manual Workflow

on:
    workflow_dispatch
# echo "OUTPUT=$(echo -n $BRANCH_NAME | openssl dgst -sha256 -binary | xxd -p)"
jobs:
    branch:
        runs-on: ubuntu-latest

        outputs:
            name: ${{ steps.name.outputs.name }}
            sha: ${{ steps.sha.outputs.sha }}

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: FranzDiebold/github-env-vars-action@v2.7.0

            - name: Branch SHA
              id: hash
              env:
                  BRANCH_NAME: ${{ env.CI_ACTION_REF_NAME_SLUG }}
              run: |
                  echo "OUTPUT=$(echo -n $BRANCH_NAME | sha256sum | head -c 40)" >> $GITHUB_ENV

            - name: Set Branch Name
              id: name
              env:
                  BRANCH_NAME: ${{ env.CI_ACTION_REF_NAME_SLUG }}
              run: |
                  echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT

            - name: Set Branch SHA
              id: sha
              env:
                  BRANCH_NAME: ${{ env.CI_ACTION_REF_NAME_SLUG }}
              run: |
                  echo "sha=${{ env.OUTPUT }}" >> $GITHUB_OUTPUT

    execute:
      needs: [branch]
      runs-on: ubuntu-latest

      steps: 
        - name: Branch Name
          run: echo ${{needs.branch.outputs.name}}

        - name: Branch SHA
          run: echo ${{needs.branch.outputs.sha}}
