name: Manual Workflow

on:
    workflow_dispatch
# echo "OUTPUT=$(echo -n $BRANCH_NAME | openssl dgst -sha256 -binary | xxd -p)"
jobs:
    branch_name:
        runs-on: ubuntu-latest

        outputs:
            name: ${{ steps.hash.outputs.branch }}

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: FranzDiebold/github-env-vars-action@v2.7.0

            - name: Set Branch Name
              id: hash
              env:
                  BRANCH_NAME: ${{ env.CI_ACTION_REF_NAME_SLUG }}
              run: |
                  echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

    branch_sha:
        needs: [branch_name]

        runs-on: ubuntu-latest

        outputs:
            sha: ${{ steps.hash.outputs.sha }}

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set Branch SHA
              id: hash
              run: |
                  echo "sha=green" >> $GITHUB_OUTPUT

    execute:
      needs: [branch_name, branch_sha]
      runs-on: ubuntu-latest

      steps: 
        - name: Branch Name
          run: echo ${{needs.branch_name.outputs.name}}

        - name: Branch SHA
          run: echo ${{needs.branch_sha.outputs.sha}}
